steps:
- id: "Executando install"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'sumGo']
  env: ['GOPATH=.']

- id: "Rodando tests"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', 'sumGo']
  env: ['GOPATH=.']

- id: "building image"
  name: 'gcr.io/cloud-builders/go'
  env: ['GOPATH=.']
  args:
  - 'build'
  - '--build-arg'
  - 'version=0.0.1'
  - '-t'
  - 'gcr.io/$PROJECT_ID/sum-go:latest'
  - '.'
images:
- 'gcr.io/$PROJECT_ID/sum-go:latest'